
# This file is part of the dinMenuPlugin package.
# (c) DineCat, 2010 http://dinecat.com/
#
# For the full copyright and license information, please view the LICENSE file,
# that was distributed with this package, or see http://www.dinecat.com/din/license.html

# Plugin schema file for Doctrine
#
# @package     dinMenuPlugin
# @subpackage  config.doctrine
# @author      Nicolay N. Zyk <relo.san@gmail.com>

#DinMenu
DinMenu:

    actAs:
        I18n:
            fields:         ['title', 'description']

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        application:        { type: 'string(50)', notnull: true }
        name:               { type: 'string(50)', notnull: true }
        is_public:          { type: 'boolean', notnull: true, default: true }
        title:              { type: 'string(150)' }
        description:        { type: 'clob(65532)' }

    indexes:
        public:             { fields: ['is_public'] }
        name:               { fields: ['application', 'name'], type: 'unique' }


#DinMenuItem
DinMenuItem:

    actAs:
        I18n:
            fields:         ['title', 'description']
        NestedSet:          { hasManyRoots: true, rootColumnName: 'root_id' }

    columns:
        id:                 { type: 'integer(4)', primary: true, autoincrement: true }
        menu_id:            { type: 'integer(4)', notnull: true }
        root_id:            { type: 'integer(4)' }
        is_public:          { type: 'boolean', notnull: true, default: false }
        title:              { type: 'string(150)' }
        module:             { type: 'string(50)' }
        action:             { type: 'string(50)' }
        uri:                { type: 'string(100)' }
        icon:               { type: 'string(50)' }
        description:        { type: 'clob(65532)' }

    indexes:
        public:             { fields: ['menu_id', 'is_public'] }

    relations:
        DinMenu:
            local:          'menu_id'
            foreign:        'id'
            type:           'one'
            foreignType:    'many'
            alias:          'Menu'
            foreignAlias:   'Items'
            onDelete:       'CASCADE'

#EOF